name: firebase_helpers
description: A package that provides various Google Firebase related services
  helpers. Provides helpers to perform queries on firestore, firebase auth etc.
version: 0.8.0
homepage: https://github.com/lohanidamodar/flutter_firebase_helpers
environment:
  sdk: '>=2.12.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
